import { axialToPixel, hexDisk } from './hex'
import {
  addRoute,
  endTurn,
  hubStock,
  removeRoute,
  spendAtFactory,
} from './logistics'
import {
  diagnoseShortageDoctor,
  fixClassLabel,
} from './shortageDoctor'
import {
  clearDraft,
  draftValidation,
  produceMark,
  saveMarkDesign,
  setDraftPart,
  unlockInvent,
} from './invent/actions'
import {
  partsForSlot,
  SANDBOX_CHASSIS,
  SANDBOX_PARTS,
  partById,
} from './invent/catalog'
import { emptyLoadout, validateMark } from './invent/validate'
import {
  PLAYER_FACTION_ID,
  RIVAL_FACTION_ID,
  hubForFaction,
  playerHub,
} from './factions'
import { createDualFactionState, createInitialState } from './initialState'
import { cloneGameState } from './clone'
import {
  attackWithOrders,
  fieldMark,
  fuelOk,
  isInSupply,
  marchToContact,
  playerArmy,
  enemyArmy,
  previewFight,
  returnToHub,
} from './combat/actions'
import {
  ARMY_SLOT_CAP,
  ATTACK_ORDER_COST,
  ORDERS_MAX,
} from './combat/types'
import {
  emptyStock,
  FACTORY_RECIPES,
  REFINE_RECIPES,
  stockOf,
  type AxialCoord,
  type BulkResourceId,
  type Faction,
  type FactionId,
  type FactoryRecipeId,
  type FixClass,
  type GameState,
  type GoodId,
  type IntermediateId,
  type MatchPreset,
  type ResourceId,
  type ResourceNode,
  type Route,
  type ShortageAlert,
  type Site,
  type SiteKind,
} from './types'

export type {
  AxialCoord,
  BulkResourceId,
  Faction,
  FactionId,
  FactoryRecipeId,
  FixClass,
  GameState,
  GoodId,
  IntermediateId,
  MatchPreset,
  ResourceId,
  ResourceNode,
  Route,
  ShortageAlert,
  Site,
  SiteKind,
}

export {
  addRoute,
  ARMY_SLOT_CAP,
  ATTACK_ORDER_COST,
  attackWithOrders,
  axialToPixel,
  clearDraft,
  cloneGameState,
  createDualFactionState,
  createInitialState,
  diagnoseShortageDoctor,
  draftValidation,
  emptyLoadout,
  emptyStock,
  endTurn,
  enemyArmy,
  FACTORY_RECIPES,
  fieldMark,
  fixClassLabel,
  fuelOk,
  hexDisk,
  hubForFaction,
  hubStock,
  isInSupply,
  marchToContact,
  ORDERS_MAX,
  partById,
  partsForSlot,
  playerArmy,
  PLAYER_FACTION_ID,
  playerHub,
  previewFight,
  produceMark,
  REFINE_RECIPES,
  removeRoute,
  returnToHub,
  RIVAL_FACTION_ID,
  SANDBOX_CHASSIS,
  SANDBOX_PARTS,
  saveMarkDesign,
  setDraftPart,
  spendAtFactory,
  stockOf,
  unlockInvent,
  validateMark,
}
